apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "product-service.fullname" . }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
automountServiceAccountToken: false
